### ISSUE TITLE
lifecycle termination may not be working correctly

### ISSUE THREAD

**Issue by bgentry** [buildkite/buildkite-aws-stack#59]
It's possible this will be resolved by #57, but... I also have some instances which are no longer running the Buildkite agent, but are still part of the ASG. I found one of these and grabbed this from its logs:

```
May  6 17:31:51 ip-10-0-1-24 lifecycled: #033[34m  INFO#033[0m[0368] Received message          #033[34minstanceid#033[0m=i-8e00f214 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  6 17:31:51 ip-10-0-1-24 lifecycled: #033[34m  INFO#033[0m[0368] Executing handler         #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-8e00f214 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  6 17:31:51 ip-10-0-1-24 lifecycled: stopping buildkite-agent gracefully
May  6 17:31:52 ip-10-0-1-24 lifecycled: Stopping buildkite-agent...
May  6 17:31:52 ip-10-0-1-24 lifecycled: Stopped
May  6 17:31:52 ip-10-0-1-24 lifecycled: buildkite-agent stopped!
May  6 17:31:52 ip-10-0-1-24 lifecycled: #033[34m  INFO#033[0m[0370] Handler finished successfully #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-8e00f214 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  6 17:31:52 ip-10-0-1-24 lifecycled: #033[34m  INFO#033[0m[0370] Lifecycle action completed successfully #033[34minstanceid#033[0m=i-8e00f214 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
```

Looks like it thinks it terminated correctly?

**Comment by lox** [comment]
I've merged those, let me know if it fixes the problems. Looks like an IAM issue.

**Comment by bgentry** [comment]
I'm still seeing this happening. This morning my cluster has 3 instances running but 0 agents. Looking on one of the boxes, I see these logs:

```
May  8 11:10:38 ip-10-0-1-8 lifecycled: #033[34m  INFO#033[0m[13508] Received message          #033[34minstanceid#033[0m=i-de1b5859 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  8 11:10:38 ip-10-0-1-8 lifecycled: #033[34m  INFO#033[0m[13508] Executing handler         #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-de1b5859 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  8 11:10:38 ip-10-0-1-8 lifecycled: stopping buildkite-agent gracefully
May  8 11:10:39 ip-10-0-1-8 lifecycled: Stopping buildkite-agent...
May  8 11:10:39 ip-10-0-1-8 lifecycled: Stopped
May  8 11:10:39 ip-10-0-1-8 lifecycled: buildkite-agent stopped!
May  8 11:10:39 ip-10-0-1-8 lifecycled: #033[34m  INFO#033[0m[13509] Handler finished successfully #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-de1b5859 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  8 11:10:39 ip-10-0-1-8 lifecycled: #033[34m  INFO#033[0m[13509] Lifecycle action completed successfully #033[34minstanceid#033[0m=i-de1b5859 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
```

**Comment by bgentry** [comment]
Just scaled up from 0 to 20 and only 1 agent came online. Others have logs like this:

```
May  9 23:00:36 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0000] Starting lifecycled daemon
May  9 23:00:36 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0000] Listening for events      #033[34mqueue#033[0m=https://sqs.us-east-1.amazonaws.com/073545338079/buildkite-AgentLifecycleQueue-1K98QE69LQVF
May  9 23:03:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0166] Received message          #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:03:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0166] Executing handler         #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:03:23 ip-10-0-2-214 lifecycled: stopping buildkite-agent gracefully
May  9 23:03:24 ip-10-0-2-214 lifecycled: Stopping buildkite-agent...
May  9 23:03:24 ip-10-0-2-214 lifecycled: Stopped
May  9 23:03:24 ip-10-0-2-214 lifecycled: buildkite-agent stopped!
May  9 23:03:24 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0167] Handler finished successfully #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:03:24 ip-10-0-2-214 lifecycled: #033[31m ERROR#033[0m[0167] Failed to complete lifecycle action #033[31merror#033[0m=ValidationError: No active Lifecycle Action found with token 81ca5887-2eda-424a-9cf5-8eb54e606d66
May  9 23:03:24 ip-10-0-2-214 lifecycled: #011status code: 400, request id: 3b807f85-163a-11e6-bec7-0d0ba5b8b4c5 #033[31minstanceid#033[0m=i-9c97c901 #033[31mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:15:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0886] Received message          #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:15:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0886] Executing handler         #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:15:23 ip-10-0-2-214 lifecycled: stopping buildkite-agent gracefully
May  9 23:15:23 ip-10-0-2-214 lifecycled: Not running
May  9 23:15:23 ip-10-0-2-214 lifecycled: buildkite-agent stopped!
May  9 23:15:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[0886] Handler finished successfully #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:15:23 ip-10-0-2-214 lifecycled: #033[31m ERROR#033[0m[0886] Failed to complete lifecycle action #033[31merror#033[0m=ValidationError: No active Lifecycle Action found with token 81ca5887-2eda-424a-9cf5-8eb54e606d66
May  9 23:15:23 ip-10-0-2-214 lifecycled: #011status code: 400, request id: e81ac9de-163b-11e6-803e-cff9ed833d1d #033[31minstanceid#033[0m=i-9c97c901 #033[31mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:18:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[1066] Received message          #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:18:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[1066] Executing handler         #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:18:23 ip-10-0-2-214 lifecycled: stopping buildkite-agent gracefully
May  9 23:18:23 ip-10-0-2-214 lifecycled: Not running
May  9 23:18:23 ip-10-0-2-214 lifecycled: buildkite-agent stopped!
May  9 23:18:23 ip-10-0-2-214 lifecycled: #033[34m  INFO#033[0m[1066] Handler finished successfully #033[34mhandler#033[0m=/usr/bin/buildkite-lifecycle-handler #033[34minstanceid#033[0m=i-9c97c901 #033[34mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
May  9 23:18:23 ip-10-0-2-214 lifecycled: #033[31m ERROR#033[0m[1066] Failed to complete lifecycle action #033[31merror#033[0m=ValidationError: No active Lifecycle Action found with token 81ca5887-2eda-424a-9cf5-8eb54e606d66
May  9 23:18:23 ip-10-0-2-214 lifecycled: #011status code: 400, request id: 53675b79-163c-11e6-830a-23e5687c63e0 #033[31minstanceid#033[0m=i-9c97c901 #033[31mtransition#033[0m=autoscaling:EC2_INSTANCE_TERMINATING
```

I have not updated to the very latest stack yet if that matters.

**Comment by bgentry** [comment]
Based on the above log (which I've seen on other brand new instances) it seems like lifecycled is malfunctioning and somehow thinking that it's being told to shut down, then killing the buildkite-agent. When it tries to answer the lifecycle hook (which I see no evidence of in my CloudWatch or ASG logs), the hook ID doesn't exist so it fails. It then continues to sit there idling.

**Comment by lox** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/HAL9000.svg/200px-HAL9000.svg.png)

**Comment by lox** [comment]
Investigating now. Thanks for the logs @bgentry

**Comment by lox** [comment]
Hrm, I thought I'd figure this out, but struggling to find a cause.

**Comment by lox** [comment]
https://github.com/lox/lifecycled/commit/ed16b16cf5a10b7575bd4966fa6cbad1c22d7cd3

**Comment by bgentry** [comment]
I think this issue is resolved now :v:
